### ISSUE TITLE
Project load failure on git describe abbrev failure

### ISSUE THREAD

**Issue by ignasi35** [dwijnand/sbt-dynver#117]
`sbt-dynver` [uses `git describe --abbrev=8`](https://github.com/dwijnand/sbt-dynver/blob/master/src/main/scala/sbtdynver/DynVerPlugin.scala#L207) and the pattern matches on [_exactly_  `8` characters](https://github.com/dwijnand/sbt-dynver/blob/master/src/main/scala/sbtdynver/DynVerPlugin.scala#L133) for the abbreviated SHA-1. 

`git describe --abbrev=<n>` produces a shortened representation of the SHA-1 of [_at least_ `n`](https://git-scm.com/docs/git-describe?origin_team=T02A7C6DG#Documentation/git-describe.txt---abbrevltngt).

`sbt-dynver` causes a `MatchError` whenever the abbreviated SHA-1 is longer than `8`:

```
[info] Loading settings for project root from build.sbt ...
[info] Resolving key references (69692 settings) ...
[error] scala.MatchError: 1.6.0-M4+51-8dc64459f+20190718-1826
[error]  (of class java.lang.String)
[error]         at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:255)
[error]         at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253)
[error]         at sbtdynver.GitDescribeOutput$Parser$$anonfun$parse$1.applyOrElse(DynVerPlugin.scala:145)
[error]         at sbtdynver.GitDescribeOutput$Parser$$anonfun$parse$1.applyOrElse(DynVerPlugin.scala:145)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
[error]         at scala.Option.map(Option.scala:146)
[error]         at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:210)
[error]         at sbtdynver.DynVerPlugin$.$anonfun$buildSettings$7(DynVerPlugin.scala:50)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] scala.MatchError: 1.6.0-M4+51-8dc64459f+20190718-1826
[error]  (of class java.lang.String)
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

which can be reproduced using [this commit](https://github.com/lagom/lagom/pull/2055/commits/8dc64459fb9db91f7c80f7735d00562c18515614) (NOTE: the link may break if/when squashing or rebasing).

The workaround is to amend the commit to get a different SHA-1 so the hash collision resolves.

**Comment by dwijnand** [comment]
https://github.com/ignasi35/lagom/tree/sbt-dynver-reproducer

**Comment by johanandren** [comment]
Just got hit by this one as well.

**Comment by davidcorcoran** [comment]
(Seeing this in sbt-synver 4.0.0 and 4.1.1)

Just hit this one too. You can see the abbreviated git hash (`0147e8bb2`) is 9 characters. 
```
$ git describe --tags --abbrev=8
v1.11.1-2-g0147e8bb2
```

So running sbt produces this stack trace:
```
scala.MatchError: v1.11.1+2-0147e8bb2
 (of class java.lang.String)
        at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:259)
        at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:257)
        at sbtdynver.GitDescribeOutput$Parser$$anonfun$parse$1.applyOrElse(DynVerPlugin.scala:145)
        at sbtdynver.GitDescribeOutput$Parser$$anonfun$parse$1.applyOrElse(DynVerPlugin.scala:145)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at scala.Option.map(Option.scala:230)
        at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:210)
        at sbtdynver.DynVerPlugin$.$anonfun$buildSettings$7(DynVerPlugin.scala:50)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[error] scala.MatchError: v1.11.1+2-0147e8bb2
```

@ignasi35  thanks for figuring it out. Saved me a lot of time...
