### ISSUE TITLE
Return of the MatchError

### ISSUE THREAD

**Issue by davegurnell** [dwijnand/sbt-dynver#138]
Hi!

I'm getting an error similar to the one in #20. I'm using:

- sbt-release-early version 2.1.1
- git version 2.21.0
- sbt installed via `brew install sbt`

Here's the full git version:

```
$ git --version
git version 2.21.0 (Apple Git-122.2)
```

The project that's failing is [this one](https://github.com/davegurnell/unindent), which hopefully will provide an easy recreate!

If I tag the repo, everything loads fine.

Here's the output from launching SBT:

```
$ sbt
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt,metals.sbt ...
[info] Loading global plugins from /Users/dave/.sbt/1.0/plugins
[info] Loading settings for project unindent-build from plugins.sbt ...
[info] Loading project definition from /Users/dave/dev/projects/unindent/project
[info] Loading settings for project unindent from build.sbt ...
[error] scala.MatchError: 1.1.1+2-513a0e62 (of class java.lang.String)
[error] Use 'last' for the full log.
```

Here's the output of `last`:

```
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? last
[debug] > Exec(early(addDefaultCommands), None, None)
[debug] > Exec(addDefaultCommands, None, None)
[debug] > Exec(early(initialize), None, None)
[debug] > Exec(initialize, None, None)
[debug] > Exec(boot, None, None)
[debug] > Exec(writeSbtVersion, None, None)
[debug] > Exec(reload, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(onFailure loadFailed, None, None)
[debug] > Exec(loadp, None, None)
[debug]       Load.loadUnit: plugins took 59.8939ms
[debug]       Load.loadUnit: defsScala took 0.242537ms
[debug] [Loading] Scanning directory /Users/dave/.sbt/1.0/plugins
[debug]         Load.loadUnit: mkEval took 5.253931ms
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/dave/.sbt/1.0/plugins, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin))), Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 13.471248 ms
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt,metals.sbt ...
[debug]           Load.resolveProject(global-plugins) took 170.595712ms
[debug]         Load.loadTransitive: finalizeProject(Project(id global-plugins, base: /Users/dave/.sbt/1.0/plugins, plugins: List(<none>))) took 190.388239ms
[debug] [Loading] Done in /Users/dave/.sbt/1.0/plugins, returning: (global-plugins)
[debug]       Load.loadUnit: loadedProjectsRaw took 543.732929ms
[debug]       Load.loadUnit: cleanEvalClasses took 6.045315ms
[debug]     Load.loadUnit(file:/Users/dave/.sbt/1.0/plugins/, ...) took 615.732936ms
[debug]   Load.apply: load took 835.790733ms
[debug]   Load.apply: resolveProjects took 3.872275ms
[debug]   Load.apply: finalTransforms took 32.258068ms
[debug]   Load.apply: config.delegates took 5.957991ms
[debug]   Load.apply: Def.make(settings)... took 255.314723ms
[debug]   Load.apply: structureIndex took 64.540858ms
[debug]   Load.apply: mkStreams took 1.173186ms
[info] Loading global plugins from /Users/dave/.sbt/1.0/plugins
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug] Load.defaultLoad until apply took 2420.649679ms
[debug]           Load.loadUnit: plugins took 29.711979ms
[debug]           Load.loadUnit: defsScala took 0.002986ms
[debug] [Loading] Scanning directory /Users/dave/dev/projects/unindent/project
[debug]             Load.loadUnit: mkEval took 0.187968ms
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/dave/dev/projects/unindent/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin))), Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(com.typesafe.sbt.SbtLicenseReport),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(com.timushev.sbt.updates.UpdatesPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(net.virtualvoid.sbt.graph.DependencyGraphPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(com.typesafe.sbt.SbtLicenseReport))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(com.timushev.sbt.updates.UpdatesPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(net.virtualvoid.sbt.graph.DependencyGraphPlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,com.typesafe.sbt.SbtLicenseReport,sbt.plugins.JvmPlugin,net.virtualvoid.sbt.graph.DependencyGraphPlugin,com.timushev.sbt.updates.UpdatesPlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 1.648089 ms
[info] Loading settings for project unindent-build from plugins.sbt ...
[debug]               Load.resolveProject(unindent-build) took 116.141328ms
[debug]             Load.loadTransitive: finalizeProject(Project(id unindent-build, base: /Users/dave/dev/projects/unindent/project, plugins: List(<none>))) took 118.282458ms
[debug] [Loading] Done in /Users/dave/dev/projects/unindent/project, returning: (unindent-build)
[debug]           Load.loadUnit: loadedProjectsRaw took 131.492701ms
[debug]           Load.loadUnit: cleanEvalClasses took 1.093856ms
[debug]         Load.loadUnit(file:/Users/dave/dev/projects/unindent/project/, ...) took 162.920539ms
[debug]       Load.apply: load took 163.955467ms
[debug]       Load.apply: resolveProjects took 0.081671ms
[debug]       Load.apply: finalTransforms took 7.562412ms
[debug]       Load.apply: config.delegates took 0.400295ms
[debug]       Load.apply: Def.make(settings)... took 96.87952ms
[debug]       Load.apply: structureIndex took 23.206188ms
[debug]       Load.apply: mkStreams took 0.002289ms
[info] Loading project definition from /Users/dave/dev/projects/unindent/project
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug]     Load.loadUnit: plugins took 560.343799ms
[debug]     Load.loadUnit: defsScala took 0.003ms
[debug] [Loading] Scanning directory /Users/dave/dev/projects/unindent
[debug]       Load.loadUnit: mkEval took 0.159724ms
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/dave/dev/projects/unindent, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin))), Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(org.scalafmt.sbt.ScalafmtPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(com.typesafe.sbt.SbtLicenseReport),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbtdynver.DynVerPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(com.timushev.sbt.updates.UpdatesPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(bintray.BintrayPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(scoverage.ScoverageSbtPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(com.typesafe.sbt.SbtPgp),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(net.virtualvoid.sbt.graph.DependencyGraphPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(xerial.sbt.Sonatype),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(ch.epfl.scala.sbt.release.ReleaseEarlyPlugin),Set(Atom(com.typesafe.sbt.SbtPgp))), Clause(Atom(ch.epfl.scala.sbt.release.ReleaseEarlyPlugin),Set(Atom(xerial.sbt.Sonatype))), Clause(Atom(ch.epfl.scala.sbt.release.ReleaseEarlyPlugin),Set(Atom(sbtdynver.DynVerPlugin))), Clause(Atom(ch.epfl.scala.sbt.release.ReleaseEarlyPlugin),Set(Atom(bintray.BintrayPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(org.scalafmt.sbt.ScalafmtPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(com.typesafe.sbt.SbtLicenseReport))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbtdynver.DynVerPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(com.timushev.sbt.updates.UpdatesPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(bintray.BintrayPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(scoverage.ScoverageSbtPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(com.typesafe.sbt.SbtPgp))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(net.virtualvoid.sbt.graph.DependencyGraphPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(xerial.sbt.Sonatype))), Clause(And(Set(Atom(com.typesafe.sbt.SbtPgp), Atom(xerial.sbt.Sonatype), Atom(sbtdynver.DynVerPlugin), Atom(bintray.BintrayPlugin))),Set(Atom(ch.epfl.scala.sbt.release.ReleaseEarlyPlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,com.typesafe.sbt.SbtPgp,com.typesafe.sbt.SbtLicenseReport,sbt.plugins.JvmPlugin,org.scalafmt.sbt.ScalafmtPlugin,scoverage.ScoverageSbtPlugin,net.virtualvoid.sbt.graph.DependencyGraphPlugin,com.timushev.sbt.updates.UpdatesPlugin,bintray.BintrayPlugin,sbt.plugins.SemanticdbPlugin,sbt.plugins.JUnitXmlReportPlugin,xerial.sbt.Sonatype,sbtdynver.DynVerPlugin,ch.epfl.scala.sbt.release.ReleaseEarlyPlugin)
[debug] Plugins.deducer#function took 2.758086 ms
[info] Loading settings for project unindent from build.sbt ...
[debug]         Load.resolveProject(unindent) took 85.979286ms
[debug]       Load.loadTransitive: finalizeProject(Project(id unindent, base: /Users/dave/dev/projects/unindent, plugins: List(<none>))) took 89.814221ms
[debug] [Loading] Done in /Users/dave/dev/projects/unindent, returning: (unindent)
[debug]     Load.loadUnit: loadedProjectsRaw took 117.263278ms
[debug]     Load.loadUnit: cleanEvalClasses took 1.312675ms
[debug]   Load.loadUnit(file:/Users/dave/dev/projects/unindent/, ...) took 679.438672ms
[debug] Load.apply: load took 681.187949ms
[debug] Load.apply: resolveProjects took 0.088716ms
[debug] Load.apply: finalTransforms took 10.435145ms
[debug] Load.apply: config.delegates took 0.379017ms
[debug] sbt-release-early: Trying to fetch `pgpPassphrase in Global` from the environment.
[error] scala.MatchError: 1.1.1+2-513a0e62 (of class java.lang.String)
[error] 	at sbtdynver.GitDescribeOutput$.parse(DynVerPlugin.scala:92)
[error] 	at sbtdynver.DynVer.$anonfun$getGitDescribeOutput$3(DynVerPlugin.scala:126)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:126)
[error] 	at sbtdynver.DynVerPlugin$.$anonfun$buildSettings$5(DynVerPlugin.scala:29)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] scala.MatchError: 1.1.1+2-513a0e62 (of class java.lang.String)
[error] Use 'last' for the full log.
[debug] > Exec(loadFailed, None, None)
[debug] > Exec(last, None, None)
```

**Comment by davegurnell** [comment]
Hang on... I just realised sbt-release-early is depending on version 2.0.0 of sbt-dynver. I assume the solution is a version bump on their part?

**Comment by davegurnell** [comment]
Ok. I forked sbt-release-early, updated the sbt-dynver dependency to 4.0.0, published locally, and tried to start SBT in my test project again. Same error but with different line numbers:

```
[error] scala.MatchError: 1.1.1+2-513a0e62+20191220-0949
[error]  (of class java.lang.String)
[error] 	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:259)
[error] 	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:257)
[error] 	at sbtdynver.GitDescribeOutput$Parser$$anonfun$parse$1.applyOrElse(DynVerPlugin.scala:145)
[error] 	at sbtdynver.GitDescribeOutput$Parser$$anonfun$parse$1.applyOrElse(DynVerPlugin.scala:145)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:210)
[error] 	at sbtdynver.DynVerPlugin$.$anonfun$buildSettings$7(DynVerPlugin.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] scala.MatchError: 1.1.1+2-513a0e62+20191220-0949
[error]  (of class java.lang.String)
[error] Use 'last' for the full log.
```

**Comment by davegurnell** [comment]
Ok so the issue is the missing `v` on the start of my tag. Historically I've tagged this repo in the format `1.2.3` instead of `v1.2.3`. I was expecting `sbt-dynver` to be unaware of the tag but not to crash. At least I have a workaround though!

**Comment by raboof** [comment]
There is a `dynverVTagPrefix` option, perhaps if you use that you can stick with the historic convention? Would be nice if we handled this more gracefully, agreed ;)

**Comment by dwijnand** [comment]
Yeah, `dynverVTagPrefix` was added to allow projects to adapt sbt-dynver, without having to retag everything (and then choose whether to delete the old tags or keep the duplication).

I'm looking at how to avoid to crash.

**Comment by dwijnand** [comment]
@davegurnell I'm having trouble reproducing.  I clone your project.  Deleted the brand new v-prefix tags and retagged 1.1.1:

```
10:14:53 $ git sl
513a0e6 (HEAD -> master, origin/master, origin/HEAD) Bump sbt-scoverage to add support for Scala 2.13.1
7018d58 Convert to sbt-release-early
2ffa24c Add Sonatype publishing plugin/settings
e2b32a3 (tag: 1.1.1) Merge branch 'develop'
25e8687 Merge pull request #2 from fkowal/scala213
dccf6f7 sbt 1.3.0
```

I've added `addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.0.0")` to plugins.sbt and... everything "works":

```
> show version
[info] 0.0.0+31-513a0e62+20191220-1013
```

It's showing that because it didn't find any v-prefixed tags.

Then if I add `dynverVTagPrefix := false` within `inThisBuild` it works even better:

```
> show version
[info] 1.1.1+3-513a0e62+20191220-1017
```

Any ideas?

**Comment by davegurnell** [comment]
Thanks for your help on this. After some careful retagging of my commits, I've worked around the problem and I'm off to the races. 

I'm still not sure why the library skips the "v-less" tag on your machine and gets hung up on it on mine. It'd be nice if it gave a more explicit error message, but it's not blocking me at any rate.

Thanks again and have a great Christmas!
