### ISSUE TITLE
Throws scala.MatchError

### ISSUE THREAD

**Issue by alexandrnikitin** [dwijnand/sbt-dynver#20]
I tried to add the plugin to one of my projects https://github.com/alexandrnikitin/bloom-filter-scala/ It throws `scala.MatchError` when loading project definition.

```
[info] Loading project definition from C:\Projects\my\bloom-filter-scala\project
scala.MatchError: v0.7.0+3-e7a84ebc+20161120-1948
 (of class java.lang.String)
	at sbtdynver.GitDescribeOutput$.parse(DynVerPlugin.scala:62)
	at sbtdynver.DynVer$$anonfun$getGitDescribeOutput$4.apply(DynVerPlugin.scala:95)
	at sbtdynver.DynVer$$anonfun$getGitDescribeOutput$4.apply(DynVerPlugin.scala:95)
	at scala.Option.map(Option.scala:145)
	at sbtdynver.DynVer.getGitDescribeOutput(DynVerPlugin.scala:95)
	at sbtdynver.DynVerPlugin$$anonfun$buildSettings$4.apply(DynVerPlugin.scala:25)
	at sbtdynver.DynVerPlugin$$anonfun$buildSettings$4.apply(DynVerPlugin.scala:25)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] scala.MatchError: v0.7.0+3-e7a84ebc+20161120-1948
 (of class java.lang.String)
[error] Use 'last' for the full log.
Invalid response.
Invalid response.
Invalid response.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
```
I tried sbt 0.13.9, 0.13.13
The branch to try: https://github.com/alexandrnikitin/bloom-filter-scala/tree/sbt-dynver

**Comment by dwijnand** [comment]
Thank you for the bug report and the clean reproduction.

I've not been able to reproduce it yet (it doesn't fail in either the REPL or when I load your project) but I'm looking into it.

**Comment by alexandrnikitin** [comment]
It didn't fail in Travis CI either. I guess it's something local to my setup. I'm looking into it too.

**Comment by dwijnand** [comment]
I've reproduced it on a Windows VM I have, so I'm thinking it's something to do with running on Windows. Either the regex (which I doubt) or the usage of git (which I find more probably).

I then tried to debug sbt-dynver on that machine, but I've run into a number of other issues that I don't understand.

I'll probably have to setup AppVeyor to test things on Windows. Any advice or ideas you have are most welcome - right now I've run out of Windows-patience :)

**Comment by alexandrnikitin** [comment]
Ahaha 😆 Yes, I run it on Windows 10.

I've also encountered some issues trying to compile and test `sbt-dynver` on Windows. E.g.

```
java.nio.file.InvalidPathException: Illegal char <
> at index 112: C:\Projects\temp\sbt-dynver\target\resolution-cache\com.dwijnand\sbt-dynver\scala_2.10\sbt_0.13\1.1.0+2-c00b8ff4
\resolved.xml.xml
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.io.File.toPath(File.java:2234)
        at coursier.Tasks$$anonfun$updateTask$1.writeIvyFiles$1(Tasks.scala:761)
        at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:893)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$41.apply(Tasks.scala:917)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$41.apply(Tasks.scala:917)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:910)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:692)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by dwijnand** [comment]
That's right. And there's no `target\resolution-cache\com.dwijnand\sbt-dynver\scala_2.10\sbt_0.13\1.1.0+2-c00b8ff4\resolved.xml.xml` to inspect..

**Comment by dwijnand** [comment]
Ah! I know what's wrong. I'm dropping the last character of calling `git describe` which is the LF, but on Windows I need to drop two, CR and LF.

I'll fix this, but I want to setup AppVeyor. Then I'll cut 1.1.1.

**Comment by fommil** [comment]
`.trim` might do a more consistent job

**Comment by alexandrnikitin** [comment]
@dwijnand Great! Thank you for such a quick fix! 👍
