### ISSUE TITLE
can not fetch sbt-dynver 1.1.1 in git@github.com:akka/akka-http.git

### ISSUE THREAD

**Issue by epiphyllum** [dwijnand/sbt-dynver#37]
```
 ~/workspace/scala/akka-http/ [master*] sbt update
[info] Loading project definition from /Users/hary/workspace/scala/akka-http/project
[info] Updating {file:/Users/hary/workspace/scala/akka-http/project/}akka-http-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	[FAILED     ] com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(doc):  (0ms)
[warn] ==== local: tried
[warn]   /Users/hary/.ivy2/local/com.dwijnand/sbt-dynver/scala_2.10/sbt_0.13/1.1.1/docs/sbt-dynver-javadoc.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.10_0.13/1.1.1/sbt-dynver-1.1.1-javadoc.jar
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/1.1.1/docs/sbt-dynver-javadoc.jar
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/1.1.1/docs/sbt-dynver-javadoc.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(doc)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: com.dwijnand#sbt-dynver;1.1.1!sbt-dynver.jar(doc)
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
```

**Comment by dwijnand** [comment]
Let's track this in https://github.com/akka/akka-http/issues/1057. I'll close this for now, we can reopen if there's an issue here.
